### ISSUE TITLE
Nrap mass resetting to 10t

### ISSUE THREAD

**Issue by Tabris83** [StupidChris/NRAP#3]
posted on the forums as-well.

i'm getting a weird problem when using the weights.

in the VAB it reports the mass correctly but on going to the launch pad the NRAP weight resets to 10t.

[Logs & Screenshots](https://www.dropbox.com/sh/9thyj4zccx0mzmi/AAAgsuuTgphogMQZoiwxXJWia?dl=0)

**Comment by Tabris83** [comment]
Bump

**Comment by tunafield** [comment]
Seems to be a conflict with kOS. kOSProcessor saves the base part mass in the craft, and later uses it to recompute the part mass to include disk space mass.

**Comment by StupidChris** [comment]
Gonna close this because of how old this is, and as I myself couldn't reproduce it back then on a clean install. If it's a kOS conflict, it should be brought up with them.
